### ISSUE TITLE
The lincurve component is broken since the interpolation formula is wrong

### ISSUE THREAD

**Issue by Clostry** [machinekit/machinekit#1390] opened 2018-07-31 13:46 UTC
Please check [https://github.com/LinuxCNC/linuxcnc/blob/master/src/hal/components/lincurve.comp#L61](https://github.com/LinuxCNC/linuxcnc/blob/master/src/hal/components/lincurve.comp#L61) and [https://github.com/machinekit/machinekit/blob/master/src/hal/i_components/lincurve.icomp#L60](https://github.com/machinekit/machinekit/blob/master/src/hal/i_components/lincurve.icomp#L60).

Clearly the machinekit  version
` out_ = ( y_val(i) + f) * (y_val(i+1) - y_val(i) ) ;`

and linuxcnc  version
` out_ =  y_val(i) + f * (y_val(i+1) - y_val(i) ) ;`

gives totally different results.

**Comment by ArcEye** [comment] 2018-07-31 14:37
The change arose from this issue.
https://github.com/machinekit/machinekit/issues/784

After alteration @presslab-us confirmed it was working correctly
https://github.com/machinekit/machinekit/commit/03deb04105675ebbe920badd215f86f0a5a39cf1#diff-6c82a87859e1bd7e1907e2add4a51921

Looks like an earlier version got pushed back when the multicore work was merged :frowning_face: 
https://github.com/machinekit/machinekit/commit/a2984ebb091109fd4c33b6a5ebe3dac1442a1e82#diff-6c82a87859e1bd7e1907e2add4a51921

I will change it back, thanks for the report

**Closed** 2018-07-31 14:45 UTC
