### ISSUE TITLE
HAL Accessor Functions

### ISSUE THREAD

**Issue by cdsteinkuehler** [machinekit/machinekit#239] opened 2014-07-06 16:22 UTC
Access to HAL types need to be done via custom accessor functions so proper memory fencing and atomic instructions can be abstracted.  This allows general HAL component code to mostly ignore the complexity of implementing proper cross-platform atomic access.

**Comment by mhaberler** [comment] 2015-07-19 06:50
@cdsteinkuehler - for designing + verifying multicore-safe accessors/modifiers it would be great to have a 'smoking gun' example like so:

- Assume HAL running on a multicore platform
- have 2 (or 2+) userland comps setting core affinity to different cores
- have them communicate through pins
- devise a consistency condition/trap/assert which reliably triggers on a memory access ordering issue (missing fence)

I can provide the first three. Do you have any ideas for the last item?

I think until the issue is fixed for good, it would not be safe to run RT AND userland threads with pins on different cores (!).

**Comment by mhaberler** [comment] 2015-07-22 07:06
re accessor design and execution model:

I think the best way forward is to do base operations on a pointer to the HAL object descriptor, not the raw memory of the HAL value.

so say setting a pin would be
````
 hal_pin_t *tool_number;
 ...
 hal_pin_set(tool_number, emcioStatus.tool.toolInSpindle);
````
instead of 
````
  *(iocontrol_data->tool_number) = emcioStatus.tool.toolInSpindle; //likewise in HAL
````
Reason: the former subsumes the latter and can be reduced to the same instructions, but if needed, attributes from the HAL object descriptor would be available. For instance, a pin marked with a write barrier bit. This is not possible if doing:
````
 hal_pin_set(&iocontrol_data->tool_number), emcioStatus.tool.toolInSpindle);
````

re memory barriers: those could in principle be added at the pin/signal operation level, at the thread level, but  I guess the right thing for a full SMP-safe setup to do is a write barrier post-hal_pin_set an a read barrier before hal_pin_get does the job, as suggested by the SMP barrier pairing style mentioned here: https://www.kernel.org/doc/Documentation/memory-barriers.txt .

Actually having the 'use_barrier' bit in the common HAL object header would also enable studying the performance impact by turning barrier handling on/off selectively. Again impossible when using the raw data, but possible when using the descriptor.

**Comment by mhaberler** [comment] 2015-07-23 11:00
I am readying https://github.com/mhaberler/machinekit/tree/halobject-header which brings some preliminary steps for HAL SMP support. Among many other improvements, all HAL obects have a [common header](https://github.com/mhaberler/machinekit/blob/halobject-header/src/hal/lib/hal_object.h#L26-L49)

you will find the _rmb and _smb flags there 

those are intended to work at the HAL scalar level like in the example above, and can be enabled on a per - object basis, so 
```
 hal_pin_set(tool_number, emcioStatus.tool.toolInSpindle);

```
would already issue barrier instructions as directed by these flags. The setter/getter inlines are still to be done.

The other use case is in thread functions: 

Either the thread function has these flags in the header, or a funct is added in halcmd like so:
`````
addf foo.funct servo [rmb] [wmb] [position]
````

this causes issuing a read barrier before  and/or a write barrier after the thread function is executed: https://github.com/mhaberler/machinekit/blob/halobject-header/src/hal/lib/hal_thread.c#L45-L78

halcmd support already in place.

note that one could do the following: assume something odd happens and a memory ordering problem is likely:
one could set the wmb/rmb flags on any/all HAL object(s) in a running config and the barriers would be issued as directed


@cdsteinkuehler - is this good enough? what else do we need?

**Comment by mhaberler** [comment] 2015-07-23 16:33
thinking about https://github.com/machinekit/machinekit/issues/239#issuecomment-123584470 and a future C API for HAL: I think the current pin API is broken as designed.

The accessor functions should operate on the pin object descriptor, not on the raw data value. Only if we use the descriptor we can get at additional attributes which might be needed downstream, like barrier info.

Also, there is no good reason to externally allocate memory for the pin per se, that memory could just as well live in the pin object descriptor or allocated automatically. The current obsession with poking around in raw data values is just that.

So here is the proposal, pre and post:

now: allocation of raw pin data in the instance struct: https://github.com/mhaberler/machinekit/blob/halobject-header/src/hal/icomp-example/icomp.c#L15-L27
with calls like so: https://github.com/mhaberler/machinekit/blob/halobject-header/src/hal/icomp-example/icomp.c#L68-L83

new API for the same code:
`````
struct inst_data {
   // NB: these are object descriptors, not data values or data value pointers!
    hal_pin_t *out;
    hal_pin_t *in;
    hal_param_t   *iter; 
..
};
...
  struct inst_data *id;
...
    if ((id->out = halx_pin_float_newf(HAL_OUT, owner_id, "%s.out", name)) == NULL)
	return -1;
     ....

// thread function code:
...
    struct inst_data *id;
   hal_pin_set(id->out, <whatever value>); // uses new accessor 
````

Now that clearly is incompatible with the old poking-around method at the API level, but it is compatible at the pin/signal/param semantics level.

That means old and new API can live just fine side by side, and instcomp can be used to migrate the most components in one go. We could automatically tag comps being 'new API' and hence SMP-safe, the same way now instantiable comps are marked (ELF section info).

opinions?

**Comment by ArcEye** [comment] 2015-07-23 16:55
Once the infrastructure is there, it will be a minor edit to instcomp to convert all existing icomps in one hit.

You get used to doing direct access in C, but it is fraught with potential dangers and
`*(pin->data) = somevalue; `
is completely inflexible.

If we switch to accessors, 
`pin->descriptor->setvalue(somevalue);`
the whole underlying code could be rewritten next year with zero impact.

**Comment by mhaberler** [comment] 2015-07-23 17:07
well my opining about the 'pin value in the descriptor' is a red herring. Nobody needs an external pointer to a basic HAL data type, as the shared memory offset is in the descriptor anyway (data_ptr_addr).

The only additional operation of this scheme is adding the shared memory base to the offset to get the address of the pin value. But that can be measured; conjecture: minimal impact. 

holding the value in the descriptor does make sense for params, but it is questionable if we should extend their life at all.

The signal value always was in the descriptor.

**Comment by mhaberler** [comment] 2015-07-24 21:22
well I thought I give it a stab and it doesnt look all that difficult

the accesors are strongly typed  and do in fact issue read/write barriers if directed by pin object attributes:  https://github.com/mhaberler/machinekit/blob/hal-acessor-API/src/hal/lib/hal_accessor.h

the object allocation in the component now looks like so: https://github.com/mhaberler/machinekit/blob/hal-acessor-API/src/hal/icomp-example/lutnv2.c#L45-L46 - no more raw data values but typed pin descriptors

and the thread function reading/writing pins: https://github.com/mhaberler/machinekit/blob/hal-acessor-API/src/hal/icomp-example/lutnv2.c#L61-L64

test branch here: https://github.com/mhaberler/machinekit/tree/hal-acessor-API
the HAL API of course needs work as it is impractical, but the whole thing builds and you can say "newinst lutnv2 foobar inputs=3 function=0xfe" and play with halcmd and linking to signals - no surprises

I think we have a go

**Comment by mhaberler** [comment] 2015-07-27 09:52
I did a first cut on atomic setters/getters: https://github.com/mhaberler/machinekit/blob/hal-accessor-API/src/hal/lib/hal_accessor.h#L13-L26

these  assume clang or gcc > 4.7.0 which I think is safe for us to assume (at gcc 4.9 throughout platforms now)

**Comment by mhaberler** [comment] 2015-07-27 18:05
for testing purposes, I built rt-preempt for the raspberry2 from here: https://github.com/emlid/linux-rt-rpi

hal-accessor-API branch is building. Now we need some verification example which traps the problem, and we can show how it is resolved using atomics and/or barriers.

**Comment by mhaberler** [comment] 2015-07-29 15:43
ok, pretty good progress

the accessor definition for pins and sigs is fairly progressed (ie does work), as do allocators and test macros: https://github.com/mhaberler/machinekit/blob/hal-plug/src/hal/lib/hal_accessor.h

I made [lutn.c](https://github.com/mhaberler/machinekit/blob/hal-plug/src/hal/icomp-example/lutnv2.c)  a showcase for the new API, which is compile-time type safe and usage is IMO simpler than the old API

pin allocation:
```c
// export per-instance HAL objects
for (i = 0; i < ip->inputs; i++) {
   ip->in[i] = halx_pin_bit_newf(HAL_IN, inst_id, "%s.in%d", name,i);
   if (bit_pin_null(ip->in[i]))
        return _halerrno;
}
ip->out = halx_pin_bit_newf(HAL_OUT, inst_id, "%s.out", name);
if (bit_pin_null(ip->out))
      return _halerrno;
````

pinops in the thread funct:
```c
for (i = 0; i < ip->inputs; i++)
  if (get_bit_pin(ip->in[i])) shift += (1 << i);

set_bit_pin(ip->out, (ip->function & (1 << shift)) != 0);
return 0;
```
have a look at the [lutnv2 demo](https://github.com/mhaberler/machinekit/blob/hal-plug/src/hal/icomp-example/lutn-demo.hal) and watch the log for barrier propagation (needs DEBUG=5)

some operations could benefit from shorthands, like for the C increment operators:
```c
	// addto etc needs a shorthand
	set_u32_pin(p->decodefail, get_u32_pin(p->decodefail) + 1);
```

plugs: pbring.c is now instantiable, uses plugs and accessor pins. Lots of code gone - this is all that is needed to make rings work from a comp, deallocation is automatic on instance/comp exit:

```c
    plug_args_t rargs = {
	.type = PLUG_READER,
	.flags = RINGTYPE_RECORD,
	.ring_name = rring,
	.owner_name = (char *) name
    };
    if ((p->to_rt_rb = halg_plug_new(1, &rargs)) == NULL)
	return _halerrno;

    plug_args_t wargs = {
	.type = PLUG_WRITER,
	.flags = RINGTYPE_RECORD,
	.ring_name = wring,
	.owner_name = (char *) name
    };
    if ((p->from_rt_rb = halg_plug_new(1, &wargs)) == NULL)
	return _halerrno;
```
to see it in action:
-  run the [halcmd script](https://github.com/mhaberler/machinekit/blob/hal-plug/src/machinetalk/msgcomponents/pbring-demo.hal),
- in separate window, run 'python pbring-demo.py'
- watch the log and output

**Comment by ArcEye** [comment] 2015-07-29 16:27
Looks good.
I will not be able to look properly and test it out until PM tomorrow.

Let you know when I have

**Comment by mhaberler** [comment] 2015-07-29 17:02
re memory reorder trap: this looks like a viable base: https://github.com/mintomic/mintomic/blob/master/tests/template.test_storeload.cpp

**Comment by ArcEye** [comment] 2015-07-30 16:45
For this record, as you know the demo hal files ran fine.

Getting there with instcomp

Now have a built in type of `pin_ptr` which can be all the types / directions etc as a pin
and thus match all the [type]_pin_ptr 's in hal.h

This .icomp now builds as a replacement for your lutnv2.c, just needs testing 
(and then I need to fix something else I broke for a couple of other icomps in the process ;) )
```
component lutnv2;

pin_ptr out bit out = 0;
pin_ptr in bit in#[pincount] = 0;
    
instanceparam int pincount = 2      "number of input pins, in0..inN";

option MAXCOUNT 5;

instanceparam int functn = 255      "lookup function - see man lut5";

function _;

author          "Michael Haberler";
description     "LUT component with configurable number of pins";
license         "GPLv2 or later";
;;

FUNCTION(_) 
{
hal_u32_t i, shift = 0;
ip = arg;

    for (i = 0; i < localpincount; i++)
        if (get_bit_pin(in(i))) shift += (1 << i);

    set_bit_pin(out, (functn & (1 << shift)) != 0);
   
    return 0;
}
```

**Comment by mhaberler** [comment] 2015-07-30 23:50
wow! cooking on shale gas, or North Sea ;-?

meanwhile, it occured to me how a migration path to a descriptor-based HAL API might work (i.e. no more direct fumbling in raw values, all wrappers)

in fact, legacy and v2 pins already live happily side by side. The key observation is - the raw pin pointer set by hal_pin_new() ff is valid only in a very limited scope: in the comp where it the pin is allocated. And it is also specific for a particular process space (some user thread or RT) due to the fact that the pointer as bent by hal_pin_new, hal_link, hal_unlink has a value which has meaning only in the allocating context. So ugly as it is, it is a very local affair.

For signals, it does not matter. They export a value location, but at a fixed place for lifetime, no pointers involved, and if that place is 'optimized by allocation in RT memory' or right in the descriptor makes no difference as long as pins point to the right place. I already migrated sigs from allocated to in-descriptor storage with moderate effort and no surprises. Both legacy and v2 pins manage to modify the right location, thats what counts for legacy functionality.

going forward, there is no way we can instill atomics/barriers with the raw C pin API in some reasonably automatic way as it stands (it would be with C++ and investigating std::atomic might yield results).

However, it is straightforward with wrappers for v2 pins. The only requirement was that v1 and v2 pin operations are handled in-sync in new/link/unlink  and the semantics are the same, so very few places to get right. Other than that v1 and v2 pins are ships in the night except they refer to the same location (with different methods at hand),

v2 pins immediately can and already have atomics and optional r/w barriers as driven by the descriptors. v1 pins will never have that except manually rewriting ops without wrappers, which I cannot see happening. But it does not hamper use of HAL to have both pins at the same time.

I have a bit limited hope that that we can introduce v2 pins into instcomp at the FUNCTION level invisibly. The C lvalue and rvalue semantics are very peculiar and there is only a limited bag of tricks one can play with macros and support functions. It might be possible by going for a C/instcomp parse tree/AST manipulations/pretty-printing back modified C code but that is a steep job. Even with the clang AST rewriting/prettyprintig API I found no obvious solution. So a lot of the viability of the new API rests on how far we can massage instcomp.

status accessors:
https://github.com/mhaberler/machinekit/blob/signals-in-descriptor/src/hal/lib/hal_accessor.h 
https://github.com/mhaberler/machinekit/blob/signals-in-descriptor/src/hal/lib/hal_priv.h#L379-L474

the macro approach is limiting, nested inlines are more promising

**Comment by ArcEye** [comment] 2015-07-31 12:17
> This .icomp now builds as a replacement for your lutnv2.c, just needs testing 

Tested and produces the same output with the test hal files as the C component, 
so lights are green for .icomps using [type]_pin_ptr to reference pins

Plenty more work yet to support all the other stuff

**Comment by mhaberler** [comment] 2015-08-07 16:08
After an extended off-list discussion on the need for atomic/barrier etc primitives, Charles and me agreed the best way forward is to use concurrencykit.org as a basis for the accessors, and maybe beyond.

See https://groups.google.com/forum/#!topic/concurrencykit/43RCsUEH0hU

**Comment by mhaberler** [comment] 2015-08-08 05:43
wading through the configure options in ck (btw configure is a shell script, not autoconf-derived):
`````
The following options will modify code generation.
  --cores=N                Specify number of cores available on target machine
  --enable-pointer-packing Assumes address encoding is subset of pointer range
  --enable-rtm             Enable restricted transactional memory (x86_64 only)
  --memory-model=N         Specify memory model (currently tso, pso or rmo)
  --vma-bits=N             Specify valid number of VMA bits

````
`--cores` only affects the regression tests and is autodetected. In case the regression tests are run during a package build, it would be great if the build could be done on a multicore machine for more realistic results.
` --enable-rtm` is not for us, not supported on all arches
`--memory-model=N` is autodetected and good enough for us BUT MIGHT COME OUT WRONG IF CROSS-BUILDING!
` --enable-pointer-packing,  --vma-bits=N` are optimizations for concurrent hash tables AFAICT, clever trick for runtime-tagged objects but optional - not for us

summary:
* ideally build on-target or fix `--memory-model=N` when cross-building (see configure)
* if running a `make regressions` during a package build, the build ideally should run on a multicore platform

**Comment by mhaberler** [comment] 2015-08-08 17:40
headway on making concurrencykit usable for us:  the Aug 8 commits on https://github.com/concurrencykit/ck/commits/master make ck work with both clang and gcc on i.MX6 quad and rpi2 ; there is a regression on single-core ARMs which should be fixed as soon as I get in touch with Samy, not a functional problem

a plea:

I would appreciate if owners of other platforms (esp Xilinx Zynq and Altera Cyclone, Exynos, Allwinner a plus) could run the ck regression tests and report results here like so:

* assure clang is installed:  `sudo apt-get install clang`
* run below script like so: `./cktest.sh >/tmp/log 2>&1`
* pastebin /tmp/log and add a link to it in this issue

`````
#!/bin/sh
REPO=/tmp/ck-test
git clone https://github.com/concurrencykit/ck.git $REPO
cd $REPO
echo testing with `gcc --version`
CC=gcc ./configure
make regressions check
make clean
echo testing with `clang --version`
CC=clang ./configure
make regressions check
`````

thanks in advance!

I will work with the ck folk through any issues. I can cover i.mx6 (cubox-i), rpi1+2, bb here.

**Comment by ArcEye** [comment] 2015-08-09 09:26
Afraid I don't have any esoteric ARM boards.
Best I can offer is an Intel 8 core amd64, certainly used all cores and success on both gcc and clang
http://mgware.co.uk/CNC/regtest.log

**Comment by mhaberler** [comment] 2015-08-09 11:07
@ArcEye - thanks, passed with flying colors!

**Comment by ArcEye** [comment] 2015-08-09 11:45
>(being a pita.. can you retest with https://github.com/mhaberler/ck.git ? we'll have to work off this fork (master) until the dust settles)

All passed
http://mgware.co.uk/CNC/regtest2.log

**Comment by the-snowwhite** [comment] 2015-08-09 15:38
About Cyclone V
I made my first test with git clone https://github.com/mhaberler/ck.git recipie
result here:
http://pastebin.com/t28sVCBw

**Comment by the-snowwhite** [comment] 2015-08-09 15:44
Second test made with https://github.com/concurrencykit/ck.git repo recipi
result here:
http://pastebin.com/YhS8erJ3

both tests have at bottom:
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
?

**Comment by mhaberler** [comment] 2015-08-09 18:23
@the-snowwhite  - could I ask you to retry with https://github.com/concurrencykit/ck.git? 

we just merged all the patches needed for machinekit and there were some fixes for arms in the pipe

**Comment by the-snowwhite** [comment] 2015-08-10 01:07
I did it again with

machinekit@debiansoc:~$ cat cktest.sh
    
    #!/bin/sh
    REPO=/tmp/ck-test

    echo platform details:
    uname -a
    cat /proc/cpuinfo

    git clone https://github.com/concurrencykit/ck.git $REPO
    cd $REPO

    echo testing with `gcc --version`
    CC=gcc ./configure
    make regressions check
    make clean

    echo testing with `clang --version`
    CC=clang ./configure
    make regressions check

with (default) gcc4.6: http://pastebin.com/n1qpJd4y

Then I installed gcc 4.7 (which also belongs to wheezy) http://pastebin.com/Tg6TG2tB

I notice last test fails with first 2 warnings:

    ../../../include/ck_ht.h:31:2: warning: #warning is a language extension [-pedantic]
    #warning ck_ht is deprecated, see ck_hm, ck_hs or ck_rhs.

and this at end:

    clang: error: assembler command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [serial] Error 1
    make[2]: Leaving directory `/tmp/ck-test/regressions/ck_ht/validate'
    make[1]: *** [all] Error 2
    make[1]: Leaving directory `/tmp/ck-test/regressions'
    make: *** [regressions] Error 2

**Comment by the-snowwhite** [comment] 2015-08-10 02:18
Being curious I tried running the tests on one of my stock configured Mk BBB's
(it has not been updated for a 10-15 or so days)
test fails at exact same place:  http://pastebin.com/Ad2fZ8KN

Are there some recent fixes in the build pipe that makes the test run on BBB ?

**Comment by ArcEye** [comment] 2015-08-10 06:07
>Then I installed gcc 4.7 (which also belongs to wheezy) http://pastebin.com/Tg6TG2tB

There are still major problems with gcc 4.7 AFAIK

If you look at any of the Debian kernels for Wheezy, they still use 4.6 to build them.

**Comment by mhaberler** [comment] 2015-08-10 07:28
@the-snowwhite - very strange on the bb, I just re-ran with ck master, see http://static.mah.priv.at/public/log.master

there is a non-functional regression which can be ignored but other than that this builds and passes, error below

let's have you reproduce on the BBB first, and then retry the Altera?


`````
----[ Testing cohort....
make[2]: Entering directory '/home/mah/ck-master/regressions/ck_cohort/validate'
./validate `expr 1 / 2` 2 1
ERROR: Number of cohorts must be greater than 0
Makefile:11: recipe for target 'check' failed
make[2]: *** [check] Error 1
make[2]: Leaving directory '/home/mah/ck-master/regressions/ck_cohort/validate'
`````

**Comment by claudiolorini** [comment] 2015-08-10 09:35
...here there are the results for the Zynq platform:
http://filebin.ca/2BdsMFTEaPRw/log
i see that are similar to 'the-snowwhite' results.

just the same using:
https://github.com/concurrencykit/ck.git

**Comment by the-snowwhite** [comment] 2015-08-10 09:36
Well I can reproduce the link: http://static.mah.priv.at/public/log.master

by modifying the script as following:

    #!/bin/sh
    REPO=/tmp/ck-test

    echo platform details:
    uname -a
    cat /proc/cpuinfo

    git clone https://github.com/concurrencykit/ck.git $REPO
    cd $REPO

    #echo testing with `gcc --version`
    #CC=gcc ./configure
    #make regressions check
    #make clean

    echo testing with `clang --version`
    #CC=clang ./configure
    CC=cc ./configure
    make regressions check

this passes in same manner on mkBBB: http://pastebin.com/NXhDSAdM

full pass(no errors) on the Cyclone V Soc: http://pastebin.com/ZHx9cBhX

changing the script (back) to:
    CC=clang ./configure
    #CC=cc ./configure

fails again mkBBB:            http://pastebin.com/yhV6LpBB

fails again: Cyclone V Soc http://pastebin.com/Ygvgpur6


BTW:
As I remembered I had been testing a self compiled kernel on that bbb I tested on a different one with same results. I did reinstall the kernel:

     sudo apt-get install reinstall linux-image-3.8.13-xenomai-r72

before testing just to be certain.

the Cyclone V Soc kernel is cross compiled with linaro 4.9.xxx as per Rocketboards recomendation.

**Comment by mhaberler** [comment] 2015-08-10 10:20
@claudiolorini @the-snowwhite - well thanks, that is already super helpful!

summary - gcc works fine, clang builds fail - correct? 

while I work with Olivier, can I ask you to try clang and the --use-cc-builtins flag, like so

`````
 CC=clang ./configure  --use-cc-builtins
 make clean regressions check
````

and post pass/failure log?  thanks!

I had not thought of crosscompiling. Need to discuss the implications - this is rather tricky stuff.

**Comment by claudiolorini** [comment] 2015-08-10 10:25
...making the modifications suggested by the-snowwhite it runs up to the end:
 http://filebin.ca/2BeFjFiPHtYv/log

**Comment by the-snowwhite** [comment] 2015-08-10 10:41
CC=clang ./configure  --use-cc-builtins
    make clean regressions check

mkBBB same failure: http://pastebin.com/t5XJDgW3

Cyclone V Soc ditto: http://pastebin.com/eh8c32ir

**Comment by mhaberler** [comment] 2015-08-10 11:08
@claudiolorini : ok on the first test (gcc), the second is just a second gcc run so no new results

do NOT use 'cc' - please use 'clang' because in your case cc is obviously aliased to gcc, not clang!

**Comment by mhaberler** [comment] 2015-08-10 11:24
@the-snowwhite - I cannot reproduce what you see. 

Did you do a 'make install' at some point from the ck dir? (if so, run 'sudo make uninstall')

I did this:   `CC=clang ./configure  --use-cc-builtins`

if I try to compile the file manually which gives the assembly errors in your log, it passes with warnings but ok:

````
mah@epig:~/ck-master$ cd regressions/ck_ht/validate/
mah@epig:~/ck-master/regressions/ck_ht/validate$ /usr/bin/clang -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -std=gnu99 -pedantic -Wall -W -Wundef -Wendif-labels -Wshadow -Wpointer-arith -Wcast-align -Wcast-qual -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wdisabled-optimization -fstrict-aliasing -O2 -pipe -Wno-parentheses  -march=armv7-a -DCK_CC_BUILTINS -fPIC -I../../../include -DCORES=1 -D__arm__ -D_GNU_SOURCE -o serial serial.c ../../../src/ck_ht.c
In file included from serial.c:27:
../../../include/ck_ht.h:31:2: warning: #warning is a language extension [-Wpedantic]
#warning ck_ht is deprecated, see ck_hm, ck_hs or ck_rhs.
 ^
../../../include/ck_ht.h:31:2: warning: ck_ht is deprecated, see ck_hm, ck_hs or ck_rhs. [-W#warnings]
2 warnings generated.
mah@epig:~/ck-master/regressions/ck_ht/validate$ 
````

This looks to me something went wrong in the configure phase, but your log doesnt show exactly

you have an old clang version, I have:
`````
mah@epig:~/ck$ clang --version
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: arm-unknown-linux-gnueabihf
Thread model: posix
````
but pretty sure this has nothing to do with it

**Comment by claudiolorini** [comment] 2015-08-10 12:57
...back to square 1
http://filebin.ca/2BezuusTRicS/log

**Comment by mhaberler** [comment] 2015-08-10 13:35
@claudiolorini - could you post the result of: 

`clang -dM -E -x c /dev/null | egrep -i '(arch|arm)'` ?
`clang -march=armv7-a -dM -E -x c /dev/null | egrep -i '(arch|arm)'` ?

that should make it possible to nail it down. Thanks for the patience!

````
mah@epig:~/ck-master/include$ clang -dM -E -x c /dev/null|egrep -i '(arch|arm)'
#define __ARMEL__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_ACLE 200
#define __ARM_ARCH 6
#define __ARM_ARCH_6K__ 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_EABI__ 1
#define __ARM_PCS 1
#define __ARM_PCS_VFP 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_SIZEOF_WCHAR_T 4
#define __ARM_VFPV2__ 1
#define __arm 1
#define __arm__ 1
````

`````
mah@epig:~/ck-master/include$ clang -march=armv7-a -dM -E -x c /dev/null|egrep -i '(arch|arm)'
#define __ARMEL__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_ACLE 200
#define __ARM_ARCH 7
#define __ARM_ARCH_7A__ 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH_PROFILE 'A'
#define __ARM_EABI__ 1
#define __ARM_NEON 1
#define __ARM_NEON__ 1
#define __ARM_PCS 1
#define __ARM_PCS_VFP 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_SIZEOF_WCHAR_T 4
#define __ARM_VFPV3__ 1
#define __arm 1
#define __arm__ 1
````

**Comment by claudiolorini** [comment] 2015-08-10 13:48
machinekit@machinekit:~/ck/ck$ clang -dM -E -x c /dev/null | egrep -i '(arch|arm)'
```
#define __ARMEL__ 1
#define __ARM_ARCH_6K__ 1
#define __arm 1
#define __arm__ 1
```
machinekit@machinekit:~/ck/ck$ clang -march=armv7-a -dM -E -x c /dev/null | egrep -i '(arch|arm)'
```
#define __ARMEL__ 1
#define __ARM_ARCH_7A__ 1
#define __ARM_NEON__ 1
#define __arm 1
#define __arm__ 1
```

**Comment by the-snowwhite** [comment] 2015-08-10 14:05
Clang 3.0 --> wheezy  Clang 3.5 --> jessie
no make install 
and I have removed /tmp/ck-test folder and /tmp/log file
when rerunning without reboot.
Meanwhile: To try something different I updated my C V Soc to jessie, and it runs (still with 3.10-ltsi-rt kernel)...
I have a preliminary result 

http://pastebin.com/6Ce7Z0nq
Note exact same kernel:

    clang --version
    Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
    Target: arm-unknown-linux-gnueabihf
    Thread model: posix

    gcc --version
    gcc (Debian 4.9.2-10) 4.9.2

**Comment by the-snowwhite** [comment] 2015-08-10 14:47
C V Soc:
Noticeable difference here:
wheezy(clang 3.0):

    machinekit@mksoc:~$ clang -dM -E -x c /dev/null | egrep -i '(arch|arm)'
    #define __ARMEL__ 1
    #define __ARM_ARCH_6K__ 1
    #define __arm 1
    #define __arm__ 1


    machinekit@mksoc:~$ clang -march=armv7-a -dM -E -x c /dev/null | egrep -i '(arch|arm)'
    #define __ARMEL__ 1
    #define __ARM_ARCH_7A__ 1
    #define __ARM_NEON__ 1
    #define __arm 1
    #define __arm__ 1

jessie(clang 3.5):

    achinekit@debiansoc:~$ clang -dM -E -x c /dev/null | egrep -i '(arch|arm)'
    #define __ARMEL__ 1
    #define __ARM_32BIT_STATE 1
    #define __ARM_ACLE 200
    #define __ARM_ARCH 6
    #define __ARM_ARCH_6K__ 1
    #define __ARM_ARCH_ISA_ARM 1
    #define __ARM_EABI__ 1
    #define __ARM_PCS 1
    #define __ARM_PCS_VFP 1
    #define __ARM_SIZEOF_MINIMAL_ENUM 4
    #define __ARM_SIZEOF_WCHAR_T 4
    #define __ARM_VFPV2__ 1
    #define __arm 1
    #define __arm__ 1

    machinekit@debiansoc:~$ clang -march=armv7-a -dM -E -x c /dev/null | egrep -i '(arch|arm)'
    #define __ARMEL__ 1
    #define __ARM_32BIT_STATE 1
    #define __ARM_ACLE 200
    #define __ARM_ARCH 7
    #define __ARM_ARCH_7A__ 1
    #define __ARM_ARCH_ISA_ARM 1
    #define __ARM_ARCH_ISA_THUMB 2
    #define __ARM_ARCH_PROFILE 'A'
    #define __ARM_EABI__ 1                                                                                                                                                                                
    #define __ARM_NEON 1                                                                                                                                                                                  
    #define __ARM_NEON__ 1                                                                                                                                                                                
    #define __ARM_PCS 1                                                                                                                                                                                   
    #define __ARM_PCS_VFP 1                                                                                                                                                                               
    #define __ARM_SIZEOF_MINIMAL_ENUM 4                                                                                                                                                                   
    #define __ARM_SIZEOF_WCHAR_T 4                                                                                                                                                                        
    #define __ARM_VFPV3__ 1                                                                                                                                                                               
    #define __arm 1
    #define __arm__ 1

**Comment by cognet** [comment] 2015-08-10 15:31
clang 3.0 is probably too old, so that is to be expected. The failure with 3.5 in barrier_dissemination however isn't, is it 100% reproducible ? Is there anything in dmesg ?

**Comment by the-snowwhite** [comment] 2015-08-10 16:15
I'm not quite sure about reproducible: (this setup is also highly experimental)
Maybe I disturbing the test with my impatience:
How long can I expect the clang test part to take on a dual core armv7 ?
I copied out the log file and it shows no errors ... yet, but it has been stuck at this place last 15-30 min:
http://pastebin.com/NEFHwuCL

**Comment by cognet** [comment] 2015-08-10 16:36
That seems way too long, that particuliar test just takes a couple seconds on my tegra2 board. 
Hmm. Can you recompile the whole thing with debug symbols (CFLAGS=-g ./configure should do the trick) and put the barrier_dissemination binary somewhere where I can download it ? Thanks !

**Comment by the-snowwhite** [comment] 2015-08-10 16:47
While the same test is still running I made a full dmesg log here: http://pastebin.com/LHDnrt4n

Hmm not much ...

    machinekit@debiansoc:~$ dmesg | tail
    [    3.553271] systemd[1]: Started Create list of required static device nodes for the current kernel.
    [    3.561503] systemd[1]: Starting Create Static Device Nodes in /dev...
    [    3.585121] systemd[1]: Starting Load Kernel Modules...
    [    3.613802] systemd[1]: Starting LSB: Set keymap...
    [    3.633338] systemd[1]: Starting Journal Service...
    [    3.681401] systemd[1]: Started Journal Service.
    [    3.988143] systemd-udevd[131]: starting version 215
    [    4.809943] systemd-journald[108]: Received request to flush runtime journal from PID 1
    [    5.170803] eth0: device MAC address 22:6f:4e:69:0d:1e
    [    7.171717] libphy: stmmac-1:01 - Link is Up - 1000/Full

**Comment by the-snowwhite** [comment] 2015-08-10 16:52
OK test passed ...!

**Comment by cognet** [comment] 2015-08-10 16:53
After 1 hour or so ?

**Comment by the-snowwhite** [comment] 2015-08-10 16:54
http://pastebin.com/Yb7ji7xr   

:-)

**Comment by the-snowwhite** [comment] 2015-08-10 16:55
yes somewhat over an hour...

**Comment by cognet** [comment] 2015-08-10 16:57
Aaah I failed to notice you were using --use-cc-builtins, I never really tried it so it may have an impact on the performances and behavior

**Comment by the-snowwhite** [comment] 2015-08-10 16:58
I had installed ccache and done this:

    With that in mind, I have decided to put the issue to rest for myself and have made myself a              
    ~/.ccache/ccache.conf containing

    run_second_cpp = true

as per: http://peter.eisentraut.org/blog/2014/12/01/ccache-and-clang-part-3/


I have no idea how this affected the time

**Comment by the-snowwhite** [comment] 2015-08-10 17:04
I could do a reboot and try without with just:
    
    CC=clang ./configure 
instead of

    CC=clang ./configure  --use-cc-builtins
?

**Comment by cognet** [comment] 2015-08-10 17:06
I'd be very curious to know if you see the same behavior

**Comment by the-snowwhite** [comment] 2015-08-10 17:07
Ok expect a report in an hour ... or ..so ...

**Comment by cognet** [comment] 2015-08-10 17:10
Thanks :)

**Comment by the-snowwhite** [comment] 2015-08-10 18:25
that would be about 1h:15: http://pastebin.com/hW5bCuuZ

funny that the logfile size stays constant after barrier_dissemination (92647 ), first updating after complete(306894), even if I log out the other account...


    machinekit@debiansoc:~$ cat cktest.sh
    #!/bin/sh
    REPO=/tmp/ck-test

    echo platform details:
    uname -a
    cat /proc/cpuinfo

    git clone https://github.com/concurrencykit/ck.git $REPO
    cd $REPO

    #echo testing with `gcc --version`
    #CC=gcc ./configure
    #make regressions check
    #make clean

    echo testing with `clang --version`
    echo and with configure --use-cc-builtins

    #CC=clang ./configure  --use-cc-builtins
    CC=clang ./configure

    #make clean regressions check
    make regressions check

Hmmm forgot to comment out the echo statement

**Comment by the-snowwhite** [comment] 2015-08-10 18:51
Yes I will do that as soon as I get back later (have to go for a social 
visit now)

**Comment by sbahra** [comment] 2015-08-10 19:13
The barrier tests will take a very very long time, especially if it's on a single core.

**Comment by the-snowwhite** [comment] 2015-08-10 22:28
OK

I was not sure if you meant:
CFLAGS=-g ./configure
or
CC=clang CFLAGS=-g ./configure

So I did the last, and test was finished when I returned...

Since the files were so small I compressed first the 
/tmp/ck-test/regressions/ck_barrier folder:
barrier:
https://drive.google.com/file/d/0BwyLvgyVIdi8dW1xRmpDb0dmRmc/view?usp=sharing

then the full /tmp/ck-test folder:
ck_test_debug:
https://drive.google.com/file/d/0BwyLvgyVIdi8d2FEOUVDaFNyczA/view?usp=sharing

All 3 files are in this gdrive shared folder (which should give direct 
open access to all the files):
ck-test folder:
https://drive.google.com/folderview?id=0BwyLvgyVIdi8fkhxbWpVN01PdEM1S2QxeFVNWTllU1lLVW9ybWYzQXFtLVpzLThPd1FpOTQ&usp=sharing

log:
log_Jessie_v3.complete-without-builtin_debug:
https://drive.google.com/file/d/0BwyLvgyVIdi8MldOTl9tdnJOdWc/view?usp=sharing

**Comment by mhaberler** [comment] 2015-08-20 07:47
thanks for all the help!

I've made good progress on using ck in HAL, and it seems we are on-route to a SMP-safe HAL which can effectively make use of several cores!

**Comment by ArcEye** [comment] 2017-07-26 11:04
This work is now all contained in Machinekit, since the multicore merge of Feb 2017

**Closed by ArcEye** 2017-07-26 11:04 UTC
Labels: enhancement
